import os

from pathlib import Path
from typing import List

TAG_NAMES = {
    "a": "a",
    "abbr": "abbr",
    "address": "address",
    "area": "area",
    "article": "article",
    "aside": "aside",
    "audio": "audio",
    "b": "b",
    "base": "base",
    "bdi": "bdi",
    "bdo": "bdo",
    "blockquote": "blockquote",
    "body": "body",
    "br": "br",
    "button": "button",
    "canvas": "canvas",
    "caption": "caption",
    "cite": "cite",
    "code": "code",
    "col": "col",
    "colgroup": "colgroup",
    "data": "data",
    "datalist": "datalist",
    "dd": "dd",
    "deleted": "del",
    "details": "details",
    "dfn": "dfn",
    "dialog": "dialog",
    "div": "div",
    "dl": "dl",
    "dt": "dt",
    "em": "em",
    "embed": "embed",
    "fieldset": "fieldset",
    "figcaption": "figcaption",
    "figure": "figure",
    "footer": "footer",
    "form": "form",
    "h1": "h1",
    "h2": "h2",
    "h3": "h3",
    "h4": "h4",
    "h5": "h5",
    "h6": "h6",
    "head": "head",
    "header": "header",
    "hr": "hr",
    "html": "html",
    "i": "i",
    "iframe": "iframe",
    "img": "img",
    "input": "input",
    "ins": "ins",
    "kbd": "kbd",
    "label": "label",
    "legend": "legend",
    "li": "li",
    "link": "link",
    "main": "main",
    "map": "map",
    "mark": "mark",
    "meta": "meta",
    "meter": "meter",
    "nav": "nav",
    "noscript": "noscript",
    "object": "object",
    "ol": "ol",
    "optgroup": "optgroup",
    "option": "option",
    "p": "p",
    "param": "param",
    "picture": "picture",
    "pre": "pre",
    "progress": "progress",
    "q": "q",
    "rp": "rp",
    "rt": "rt",
    "ruby": "ruby",
    "s": "s",
    "samp": "samp",
    "script": "script",
    "section": "section",
    "select": "select",
    "small": "small",
    "source": "source",
    "span": "span",
    "strong": "strong",
    "style": "style",
    "sub": "sub",
    "summary": "summary",
    "sup": "sup",
    "svg": "svg",
    "table": "table",
    "title": "title",
    "tbody": "tbody",
    "td": "td",
    "template": "template",
    "textarea": "textarea",
    "tfoot": "tfoot",
    "th": "th",
    "thead": "thead",
    "time": "time",
    "tile": "tile",
    "tr": "tr",
    "track": "track",
    "u": "u",
    "ul": "ul",
    "var": "var",
    "video": "video",
    "wbr": "wbr",
}

TEMPLATE = """class {class_name}(Element):
    def __init__(self, *children: T_element, **attributes: Any) -> None:
        super().__init__("{tag_name}", *children, **attributes)

"""

if __name__ == "__main__":
    CWD = Path(os.path.dirname(__file__))

    hydrogen_path = CWD.joinpath("src/hydrogen")

    tags_path = hydrogen_path.joinpath("tags.py")

    tag_strings: List[str] = [
        "from __future__ import annotations",
        "",
        "from typing import Any",
        "",
        "from hydrogen.elements import Element, T_element",
        "",
        "",
    ]

    for class_name, tag_name in TAG_NAMES.items():
        tag_strings.append(TEMPLATE.format(class_name=class_name, tag_name=tag_name))

    tags_path.write_text("\n".join(tag_strings))
